defaults:
  - ikea_dense
  - _self_


# Overrides
id: IKEASawyerGen-v0
ikea_cfg:
  class_name: FurnitureSawyerGenEnv
  config_name: ikea_gen
  max_episode_steps: 2000
  control_type: ik
  furniture_name: table_lack_0825
  unity:
    use_unity: false
  auto_align: false
  alignment_pos_dist: 0.02
  alignment_rot_dist_up: 0.99
  alignment_rot_dist_forward: 0.99
  alignment_project_dist: 0.0


  # Demonstration generation
  start_count: null
  n_demos: 20
